
  - name: Upgrade packages
    yum:
      name: '*'
      state: latest

  - name: Add kubernetes repo 
    copy:
      src: files/kubernetes.repo
      dest: /etc/yum.repos.d/kubernetes.repo

  - selinux:
      policy: targeted
      state: permissive

  - name: Install packages
    yum:
      name: "{{ item }}"
      state: latest
    with_items:
      - docker
      - kubelet
      - kubeadm
      - dnsmasq

  - name: Install kubeadm
    yum:
      name: kubeadm-1.6.7-0
      state: present

  - name: Start and enable services
    service:
      name: "{{ item }}"
      state: started
      enabled: yes
    with_items:
      - docker
      - kubelet

  - name: Vagrant workaround
    file:
      content: "1"
      dest: /proc/sys/net/bridge/bridge-nf-call-iptables
    when: vagrant is defined
