
  - name: yum update
    command: yum update -y

  - name: Upgrade packages
    yum:
      name: "*"
      state: latest

  - name: Add kubernetes repo 
    copy:
      src: files/kubernetes.repo
      dest: /etc/yum.repos.d/kubernetes.repo

  - name: yum update
    command: yum update -y

  - selinux:
      policy: targeted
      state: permissive

  # Latest kubeadm is broken
  - name: Install kubeadm
    yum:
      name: kubeadm-1.6.7-0
      state: present
    register: kubeadm_install

  - name: Install packages
    yum:
      name: "{{ item }}"
      state: latest
    with_items:
      - docker
      - kubelet
      - dnsmasq

  - name: Start and enable services
    service:
      name: "{{ item }}"
      state: started
      enabled: yes
    with_items:
      - docker
      - kubelet
      - dnsmasq

  - name: get ip
    command: hostname -i
    register: hostname_ip
    when: vagrant is defined

  - set_fact:
      ip_addr: "{{ hostname_ip.stdout }}"

  - name: Vagrant workaround
    template:
      src: resolv.conf.vagrant
      dest: /etc/resolv.conf
      mode: 0444
      #command: chattr +i /etc/resolv.conf
    when: vagrant is defined

  - name: Vagrant workaround
    copy:
      src: files/dnsmasq.conf.vagrant
      dest: /etc/dnsmasq.conf
    when: vagrant is defined

  - name: restart dnsmasq
    service:
      name: dnsmasq
      state: restarted
    when: vagrant is defined

  - name: set bridge-nf-call-iptables to 1
    command: sysctl net.bridge.bridge-nf-call-iptables=1
    when: vagrant is defined
    become: true
