
  - name: Open ports
    firewalld:
      port: "{{ item }}/tcp"
      permanent: true
      state: enabled
    with_items:
      - "6443"
      - "10250"
    register: ports
    when: not vagrant is defined

  - name: Restart firewalld
    service:
      name: firewalld
      state: restarted
    when: ports.changed

  - name: Init kubeadm. This may take a few minutes.
    command: kubeadm init
    when: kubeadm_install.changed
    register: kubeadm_init
    failed_when: "'FAILED' in kubeadm_init.stderr"

  - name: create .kube
    file:
      path: /home/{{ user_name }}/.kube
      state: directory
      owner: "{{ user_name }}"
      group: "{{ user_name }}"

  - name: copy admin.conf
    copy:
      src: /etc/kubernetes/admin.conf
      dest: /home/{{ user_name }}/.kube/config
      remote_src: true
      owner: "{{ user_name }}"
      group: "{{ user_name }}"

  - name: Export KUBECONFIG
    command: echo export KUBECONFIG=/home/{{ user_name }}/.kube/config >> /home/{{ user_name }}/.bashrc
    when: kubeadm_init.changed

  - name: Source the bashrc file
    shell: source ~/.bashrc
    become: false

  - name: Initialize network
    command: kubectl apply -f https://git.io/weave-kube-1.6
    when: kubeadm_init.changed
    become: false
    register: network

  - name: Remove master taint
    command: kubectl taint nodes --all node-role.kubernetes.io/master-
    become: false
    when: network.changed

